baseURL = "https://localhost:1313/"
title = "Hugo Theme"
theme = "demo-theme"

[params]
  AuthorName = "Demo"
  GitHubUser = ""
  ListOfFoo = ["foo1", "foo2"]
  SidebarRecentLimit = 5
  Subtitle = "Hugo is Absurdly Fast!"

[permalinks]
  posts = "/:year/:month/:title/"

# main menu
[[menu.main]]
    name = "Home"
    url = ""
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

# Add footer contents here
[[params.footer]]
    name = "221B, Baker Street"
    url = false
[[params.footer]]
    name = "Mail"
    url = "mailto:"